### ISSUE TITLE
Paths returned by download_all don't point to an existing path

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag-sentinelsat#10]
https://github.com/CS-SI/eodag/pull/244 will update the paths returned by the download methods of EODAG. It'd be nice to update this plugin too.

I have observed that right now the paths returned by `download_all` don't actually point to any file or directory. For example:
* Returned path: '/tmp/S2B_MSIL1C_20210321T104639_N0209_R051_T31TEJ_20210321T130616'
* Path of the archive: '/tmp/S2B_MSIL1C_20210301T104859_N0209_R051_T31TEJ_20210301T115849.zip'
* Path of the extracted product: '/tmp/S2B_MSIL1C_20210301T104859_N0209_R051_T31TEJ_20210301T115849.SAFE'

In the core plugins, when a product is extracted, a directory is first created in `outputs_prefix` whose name is `product.properties["title"]`, then the product is extracted in there and the returned path points to that subfolder, e.g. `/tmp/S2B_MSIL1C_20210321T104639_N0209_R051_T31TEJ_20210321T130616/S2B_MSIL1C_20210321T104639_N0209_R051_T31TEJ_20210321T130616.SAFE`

@remi-braun since we've just talked about that, would it be OK for you if this plugin was updated to be more in sync with the core? I have the feeling that it would overall benefit from behaving more closely to the core, which means the core has to provide some utilities to make it easier ;)

**Comment by remi-braun** [comment]
Yes of course !
The ideal is that the course of this plugin stays as parallel as possible to the core 😉 

If I get this right, this is an outside plugin because of `sentinelsat`'s licence ?

**Comment by maximlt** [comment]
I don't know why exactly this is an external plugin. One thing that is sure though is that having it in core would add another dependency, while EODAG tries not to have too many of them.

OK so in the future there will surely be changes made to this plugin to align it with the core, thanks for your feedback!

**Comment by remi-braun** [comment]
As far as I'm concerned, I always use this plugin **with** the core, switching between providers so it makes sense to me they behave similarly 😄

**Comment by sbrunato** [comment]
> If I get this right, this is an outside plugin because of `sentinelsat`'s licence ?

yes, `sentinelsat` is licensed under the [GPL v3.0](https://github.com/sentinelsat/sentinelsat/blob/main/LICENSE) license (and so is [eodag-sentinelsat](https://github.com/CS-SI/eodag-sentinelsat/blob/develop/LICENSE)), but EODAG is licensed under [Apache v2.0](https://github.com/CS-SI/eodag/blob/develop/LICENSE).
