### ISSUE TITLE
Apihub URL has changed

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag-sentinelsat#28]
For a while I was unable to download Sentinel data from scihub because of invalid credentials (although my credentials worked perfectly on the DHUS)
Then I saw that: https://scihub.copernicus.eu/news/News00868

> Open Access Hub users are informed that the API Hub URL has changed from https://scihub.copernicus.eu/apihub/ to https://apihub.copernicus.eu/apihub/ as of 28 April 2021.

My issue was resolved when changing the old URL to the new :)

**Comment by remi-braun** [comment]
My bad I still had an old version and I haven't noticed it 😓

**Comment by remi-braun** [comment]
Still continuing my monologue, this has been corrected but not released. 
Have you an idea when you will release it ?

**Comment by remi-braun** [comment]
**Workaround**: add  `endpoint: "https://apihub.copernicus.eu/apihub/"` in the configuration file (under `scihub/api`).

**Comment by sbrunato** [comment]
Hello @remi-braun , sorry I am interrupting your monologue :smile: . 
The next release will be as soon as possible, including LTA products handling (almost done!). Thanks
