### ISSUE TITLE
Copernicus POD Hub

### ISSUE THREAD

**Issue by iliion** [CS-SI/eodag-sentinelsat#35]
The Copernicus Open access hub offers another endpoint for downloading products.
Namely this is the following: `https://scihub.copernicus.eu/gnss/odata/..` and from what I can understand it has the same functionality as the `https://apihub.copernicus.eu/apihub/`. 

Maybe it would be good to have both endpoints as differents providers that can be used by EODAG in order to download products.

For example `scihub` and `scihub-gnss`. 

_Pinging @sbrunato , @geonux_

**Comment by sbrunato** [comment]
service is not available any more
