### ISSUE TITLE
Inherit from QueryStringSearch instead of ODataV4Search

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag-sentinelsat#7]
Not a bug per say, but I noticed that this API plugin inherits from `ODataV4Search`. I couldn't figure out why exactly. `ODataV4Search` itself inherits from `QueryStringSearch` and has 2 specialized methods: `do_search` and `get_metadata_search_url`. None of them seems to be used by the plugin itself.

It uses however `normalize_results`, `map_product_type`, `get_product_type_def_params` and `build_query_string`, which are all methods which all belong to `QueryStringSearch`.

I guess it could just inherit from `QueryStringSearch`.

**Comment by remi-braun** [comment]
Yes this is my doing haha. 
I made this inheritance a long time ago and I was using more eodag functions then. 
Maybe I was using some of `ODataV4Search` plugin, I don't remember.
But now it sure seems to be useless 😉

**Comment by maximlt** [comment]
No problem :) I was just having a look at the code and noticed that. This could be changed when the issue with the datetime properties is fixed.
